.\" Man page for ukui-touch-translator-config
.TH UKUITOUCH 1 "19 Augest 2020" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
ukui-touch-translator-config \- The config tool of touch for the UKUI Desktop Environment
.SH "SYNOPSIS"
.B ukui-touch-translator-config
.SH "DESCRIPTION"
The \fBukui-touch-translator-config\fR provides a graphics shortcut config interface.
.PP
This manual page documents the \fBukui-menu\fR command.
.P
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://github.com/ukui/libinput-touch-translator/issues
.SH "AUTHORS"
.SS This Man Page has been written for the UKUI Desktop Environment by:
larue <lanyue@kylinos.cn> (2020)
.SH "SEE ALSO"
